language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy2.7"
  - "pypy3.5"
before_script:
  - wget https://github.com/kr/beanstalkd/archive/v1.10.tar.gz -O /tmp/beanstalkd.tar.gz
  - tar -C /tmp -xvf /tmp/beanstalkd.tar.gz
  - pushd /tmp/beanstalkd-1.10 && make && export BEANSTALKD_PATH="$(pwd)/beanstalkd" && popd
install:
  - "pip install -r requirements-tests.txt"
  - "pip install ."
script: "py.test --cov=pystalk --cov-report=term-missing tests/"
