name: 'CI'

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '0 19 * * 1'

jobs:
  run-tests:
    env:
      BEANSTALK_VERSION: '1.12'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pythonversion: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@v7
      - name: cache beanstalkd
        id: cache-beanstalkd
        uses: actions/cache@v6
        with:
          path: ~/beanstalks
          key: ${{ runner.os }}-${{ env.BEANSTALK_VERSION }}
      - name: build beanstalkd
        if: steps.cache-beanstalkd.cache_hit != 'true'
        run: |
          mkdir -p ~/beanstalks
          curl -LJ -o /tmp/beanstalkd.tar.gz https://github.com/beanstalkd/beanstalkd/archive/v${{ env.BEANSTALK_VERSION }}.tar.gz
          tar -C /tmp -xvf /tmp/beanstalkd.tar.gz
          cd /tmp/beanstalkd-${{ env.BEANSTALK_VERSION }}
          make
          mv beanstalkd ~/beanstalks/
      - name: set up python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.pythonversion }}
      - uses: extractions/setup-just@v4
      - name: install dependencies
        run: just install
      - name: lint with flake8
        run: just lint
      - name: test with pytest
        run: just test
        env:
          BEANSTALKD_PATH: ~/beanstalks/beanstalkd
      - name: check mypy
        run: just mypy
  docs:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4
      - uses: actions/setup-python@v7
        with:
          python-version: '3.14'
      - name: Generate Docs
        run: just docs
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
